
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Asia/Almaty",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 18468,  // UTC offset 18468, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-1441170468, FixedTimespan {  // 1924-05-01T18:52:12.000 UTC
            offset: 18000,  // UTC offset 18000, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+05"),
        }),
        (-1247547600, FixedTimespan {  // 1930-06-20T19:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (354909600, FixedTimespan {  // 1981-03-31T18:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (370717200, FixedTimespan {  // 1981-09-30T17:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (386445600, FixedTimespan {  // 1982-03-31T18:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (402253200, FixedTimespan {  // 1982-09-30T17:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (417981600, FixedTimespan {  // 1983-03-31T18:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (433789200, FixedTimespan {  // 1983-09-30T17:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (449604000, FixedTimespan {  // 1984-03-31T18:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (465336000, FixedTimespan {  // 1984-09-29T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (481060800, FixedTimespan {  // 1985-03-30T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (496785600, FixedTimespan {  // 1985-09-28T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (512510400, FixedTimespan {  // 1986-03-29T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (528235200, FixedTimespan {  // 1986-09-27T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (543960000, FixedTimespan {  // 1987-03-28T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (559684800, FixedTimespan {  // 1987-09-26T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (575409600, FixedTimespan {  // 1988-03-26T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (591134400, FixedTimespan {  // 1988-09-24T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (606859200, FixedTimespan {  // 1989-03-25T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (622584000, FixedTimespan {  // 1989-09-23T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (638308800, FixedTimespan {  // 1990-03-24T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (654638400, FixedTimespan {  // 1990-09-29T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (670363200, FixedTimespan {  // 1991-03-30T20:00:00.000 UTC
            offset: 21600,  // UTC offset 18000, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+06"),
        }),
        (686091600, FixedTimespan {  // 1991-09-28T21:00:00.000 UTC
            offset: 18000,  // UTC offset 18000, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+05"),
        }),
        (695768400, FixedTimespan {  // 1992-01-18T21:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (701812800, FixedTimespan {  // 1992-03-28T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (717537600, FixedTimespan {  // 1992-09-26T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (733262400, FixedTimespan {  // 1993-03-27T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (748987200, FixedTimespan {  // 1993-09-25T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (764712000, FixedTimespan {  // 1994-03-26T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (780436800, FixedTimespan {  // 1994-09-24T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (796161600, FixedTimespan {  // 1995-03-25T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (811886400, FixedTimespan {  // 1995-09-23T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (828216000, FixedTimespan {  // 1996-03-30T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (846360000, FixedTimespan {  // 1996-10-26T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (859665600, FixedTimespan {  // 1997-03-29T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (877809600, FixedTimespan {  // 1997-10-25T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (891115200, FixedTimespan {  // 1998-03-28T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (909259200, FixedTimespan {  // 1998-10-24T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (922564800, FixedTimespan {  // 1999-03-27T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (941313600, FixedTimespan {  // 1999-10-30T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (954014400, FixedTimespan {  // 2000-03-25T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (972763200, FixedTimespan {  // 2000-10-28T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (985464000, FixedTimespan {  // 2001-03-24T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (1004212800, FixedTimespan {  // 2001-10-27T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (1017518400, FixedTimespan {  // 2002-03-30T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (1035662400, FixedTimespan {  // 2002-10-26T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (1048968000, FixedTimespan {  // 2003-03-29T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (1067112000, FixedTimespan {  // 2003-10-25T20:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
        (1080417600, FixedTimespan {  // 2004-03-27T20:00:00.000 UTC
            offset: 25200,  // UTC offset 21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+07"),
        }),
        (1099162800, FixedTimespan {  // 2004-10-30T19:00:00.000 UTC
            offset: 21600,  // UTC offset 21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+06"),
        }),
    ]},
};


