
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Asia/Baku",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 11964,  // UTC offset 11964, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-1441163964, FixedTimespan {  // 1924-05-01T20:40:36.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (-405140400, FixedTimespan {  // 1957-02-28T21:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (354916800, FixedTimespan {  // 1981-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (370724400, FixedTimespan {  // 1981-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (386452800, FixedTimespan {  // 1982-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (402260400, FixedTimespan {  // 1982-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (417988800, FixedTimespan {  // 1983-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (433796400, FixedTimespan {  // 1983-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (449611200, FixedTimespan {  // 1984-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (465343200, FixedTimespan {  // 1984-09-29T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (481068000, FixedTimespan {  // 1985-03-30T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (496792800, FixedTimespan {  // 1985-09-28T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (512517600, FixedTimespan {  // 1986-03-29T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (528242400, FixedTimespan {  // 1986-09-27T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (543967200, FixedTimespan {  // 1987-03-28T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (559692000, FixedTimespan {  // 1987-09-26T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (575416800, FixedTimespan {  // 1988-03-26T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (591141600, FixedTimespan {  // 1988-09-24T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (606866400, FixedTimespan {  // 1989-03-25T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (622591200, FixedTimespan {  // 1989-09-23T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (638316000, FixedTimespan {  // 1990-03-24T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (654645600, FixedTimespan {  // 1990-09-29T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("BAKT"),
        }),
        (670370400, FixedTimespan {  // 1991-03-30T22:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("BAKST"),
        }),
        (683496000, FixedTimespan {  // 1991-08-29T20:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (686098800, FixedTimespan {  // 1991-09-28T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (701823600, FixedTimespan {  // 1992-03-28T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (717544800, FixedTimespan {  // 1992-09-26T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (828234000, FixedTimespan {  // 1996-03-31T01:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (846378000, FixedTimespan {  // 1996-10-27T01:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (859680000, FixedTimespan {  // 1997-03-30T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (877824000, FixedTimespan {  // 1997-10-26T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (891129600, FixedTimespan {  // 1998-03-29T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (909273600, FixedTimespan {  // 1998-10-25T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (922579200, FixedTimespan {  // 1999-03-28T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (941328000, FixedTimespan {  // 1999-10-31T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (954028800, FixedTimespan {  // 2000-03-26T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (972777600, FixedTimespan {  // 2000-10-29T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (985478400, FixedTimespan {  // 2001-03-25T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1004227200, FixedTimespan {  // 2001-10-28T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1017532800, FixedTimespan {  // 2002-03-31T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1035676800, FixedTimespan {  // 2002-10-27T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1048982400, FixedTimespan {  // 2003-03-30T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1067126400, FixedTimespan {  // 2003-10-26T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1080432000, FixedTimespan {  // 2004-03-28T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1099180800, FixedTimespan {  // 2004-10-31T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1111881600, FixedTimespan {  // 2005-03-27T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1130630400, FixedTimespan {  // 2005-10-30T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1143331200, FixedTimespan {  // 2006-03-26T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1162080000, FixedTimespan {  // 2006-10-29T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1174780800, FixedTimespan {  // 2007-03-25T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1193529600, FixedTimespan {  // 2007-10-28T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1206835200, FixedTimespan {  // 2008-03-30T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1224979200, FixedTimespan {  // 2008-10-26T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1238284800, FixedTimespan {  // 2009-03-29T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1256428800, FixedTimespan {  // 2009-10-25T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1269734400, FixedTimespan {  // 2010-03-28T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1288483200, FixedTimespan {  // 2010-10-31T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1301184000, FixedTimespan {  // 2011-03-27T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1319932800, FixedTimespan {  // 2011-10-30T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1332633600, FixedTimespan {  // 2012-03-25T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1351382400, FixedTimespan {  // 2012-10-28T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1364688000, FixedTimespan {  // 2013-03-31T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1382832000, FixedTimespan {  // 2013-10-27T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1396137600, FixedTimespan {  // 2014-03-30T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1414281600, FixedTimespan {  // 2014-10-26T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
        (1427587200, FixedTimespan {  // 2015-03-29T00:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("AZST"),
        }),
        (1445731200, FixedTimespan {  // 2015-10-25T00:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("AZT"),
        }),
    ]},
};


