[package]
name = "grokdb2"
version = "0.1.0"
authors = ["Alberto Leal <mailforalberto@gmail.com>"]

[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`

[dependencies.hyper]
version = "0.9.6"

# this is copied
# [dependencies.reroute]
# version = "0.1.1"

[dependencies.rusqlite]
version = "0.7.2"
features = ["functions", "backup"]

[dependencies]
regex = "0.1"
horrorshow = "0.5"
url = "1.1"
conduit-mime-types = "0.7.3"
lazy_static = "0.2.1"
mime = "0.2.0"
# html5ever = "0.5.4"
# tendril = "0.2.2"
