[package]
name = "grokdb2"
version = "0.1.0"
authors = ["Alberto Leal <mailforalberto@gmail.com>"]

[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`

[dependencies.hyper]
version = "0.9.4"

# [dependencies.reroute]
# version = "0.1.1"

[dependencies]
regex = "0.1"
horrorshow = "0.5"
