
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Pacific/Easter",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: -24152,  // UTC offset -24152, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-2524497448, FixedTimespan {  // 1890-01-01T06:42:32.000 UTC
            offset: -24152,  // UTC offset -24152, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EMT"),
        }),
        (-1178126248, FixedTimespan {  // 1932-09-01T06:42:32.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (-36619200, FixedTimespan {  // 1968-11-03T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (-23922000, FixedTimespan {  // 1969-03-30T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (-3355200, FixedTimespan {  // 1969-11-23T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (7527600, FixedTimespan {  // 1970-03-29T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (24465600, FixedTimespan {  // 1970-10-11T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (37767600, FixedTimespan {  // 1971-03-14T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (55915200, FixedTimespan {  // 1971-10-10T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (69217200, FixedTimespan {  // 1972-03-12T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (87969600, FixedTimespan {  // 1972-10-15T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (100666800, FixedTimespan {  // 1973-03-11T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (118209600, FixedTimespan {  // 1973-09-30T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (132116400, FixedTimespan {  // 1974-03-10T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (150868800, FixedTimespan {  // 1974-10-13T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (163566000, FixedTimespan {  // 1975-03-09T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (182318400, FixedTimespan {  // 1975-10-12T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (195620400, FixedTimespan {  // 1976-03-14T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (213768000, FixedTimespan {  // 1976-10-10T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (227070000, FixedTimespan {  // 1977-03-13T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (245217600, FixedTimespan {  // 1977-10-09T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (258519600, FixedTimespan {  // 1978-03-12T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (277272000, FixedTimespan {  // 1978-10-15T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (289969200, FixedTimespan {  // 1979-03-11T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (308721600, FixedTimespan {  // 1979-10-14T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (321418800, FixedTimespan {  // 1980-03-09T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (340171200, FixedTimespan {  // 1980-10-12T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (353473200, FixedTimespan {  // 1981-03-15T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (371620800, FixedTimespan {  // 1981-10-11T04:00:00.000 UTC
            offset: -21600,  // UTC offset -25200, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (384922800, FixedTimespan {  // 1982-03-14T03:00:00.000 UTC
            offset: -25200,  // UTC offset -25200, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (384948000, FixedTimespan {  // 1982-03-14T10:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (403070400, FixedTimespan {  // 1982-10-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (416372400, FixedTimespan {  // 1983-03-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (434520000, FixedTimespan {  // 1983-10-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (447822000, FixedTimespan {  // 1984-03-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (466574400, FixedTimespan {  // 1984-10-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (479271600, FixedTimespan {  // 1985-03-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (498024000, FixedTimespan {  // 1985-10-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (510721200, FixedTimespan {  // 1986-03-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (529473600, FixedTimespan {  // 1986-10-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (545194800, FixedTimespan {  // 1987-04-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (560923200, FixedTimespan {  // 1987-10-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (574225200, FixedTimespan {  // 1988-03-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (592372800, FixedTimespan {  // 1988-10-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (605674800, FixedTimespan {  // 1989-03-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (624427200, FixedTimespan {  // 1989-10-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (637124400, FixedTimespan {  // 1990-03-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (653457600, FixedTimespan {  // 1990-09-16T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (668574000, FixedTimespan {  // 1991-03-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (687326400, FixedTimespan {  // 1991-10-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (700628400, FixedTimespan {  // 1992-03-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (718776000, FixedTimespan {  // 1992-10-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (732078000, FixedTimespan {  // 1993-03-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (750225600, FixedTimespan {  // 1993-10-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (763527600, FixedTimespan {  // 1994-03-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (781675200, FixedTimespan {  // 1994-10-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (794977200, FixedTimespan {  // 1995-03-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (813729600, FixedTimespan {  // 1995-10-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (826426800, FixedTimespan {  // 1996-03-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (845179200, FixedTimespan {  // 1996-10-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (859690800, FixedTimespan {  // 1997-03-30T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (876628800, FixedTimespan {  // 1997-10-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (889930800, FixedTimespan {  // 1998-03-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (906868800, FixedTimespan {  // 1998-09-27T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (923194800, FixedTimespan {  // 1999-04-04T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (939528000, FixedTimespan {  // 1999-10-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (952830000, FixedTimespan {  // 2000-03-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (971582400, FixedTimespan {  // 2000-10-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (984279600, FixedTimespan {  // 2001-03-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1003032000, FixedTimespan {  // 2001-10-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1015729200, FixedTimespan {  // 2002-03-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1034481600, FixedTimespan {  // 2002-10-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1047178800, FixedTimespan {  // 2003-03-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1065931200, FixedTimespan {  // 2003-10-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1079233200, FixedTimespan {  // 2004-03-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1097380800, FixedTimespan {  // 2004-10-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1110682800, FixedTimespan {  // 2005-03-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1128830400, FixedTimespan {  // 2005-10-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1142132400, FixedTimespan {  // 2006-03-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1160884800, FixedTimespan {  // 2006-10-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1173582000, FixedTimespan {  // 2007-03-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1192334400, FixedTimespan {  // 2007-10-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1206846000, FixedTimespan {  // 2008-03-30T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1223784000, FixedTimespan {  // 2008-10-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1237086000, FixedTimespan {  // 2009-03-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1255233600, FixedTimespan {  // 2009-10-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1270350000, FixedTimespan {  // 2010-04-04T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1286683200, FixedTimespan {  // 2010-10-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1304823600, FixedTimespan {  // 2011-05-08T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1313899200, FixedTimespan {  // 2011-08-21T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1335668400, FixedTimespan {  // 2012-04-29T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1346558400, FixedTimespan {  // 2012-09-02T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1367118000, FixedTimespan {  // 2013-04-28T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1378612800, FixedTimespan {  // 2013-09-08T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1398567600, FixedTimespan {  // 2014-04-27T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1410062400, FixedTimespan {  // 2014-09-07T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1463281200, FixedTimespan {  // 2016-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1471147200, FixedTimespan {  // 2016-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1494730800, FixedTimespan {  // 2017-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1502596800, FixedTimespan {  // 2017-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1526180400, FixedTimespan {  // 2018-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1534046400, FixedTimespan {  // 2018-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1557630000, FixedTimespan {  // 2019-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1565496000, FixedTimespan {  // 2019-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1589079600, FixedTimespan {  // 2020-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1596945600, FixedTimespan {  // 2020-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1620529200, FixedTimespan {  // 2021-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1629000000, FixedTimespan {  // 2021-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1652583600, FixedTimespan {  // 2022-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1660449600, FixedTimespan {  // 2022-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1684033200, FixedTimespan {  // 2023-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1691899200, FixedTimespan {  // 2023-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1715482800, FixedTimespan {  // 2024-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1723348800, FixedTimespan {  // 2024-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1746932400, FixedTimespan {  // 2025-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1754798400, FixedTimespan {  // 2025-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1778382000, FixedTimespan {  // 2026-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1786248000, FixedTimespan {  // 2026-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1809831600, FixedTimespan {  // 2027-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1818302400, FixedTimespan {  // 2027-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1841886000, FixedTimespan {  // 2028-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1849752000, FixedTimespan {  // 2028-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1873335600, FixedTimespan {  // 2029-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1881201600, FixedTimespan {  // 2029-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1904785200, FixedTimespan {  // 2030-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1912651200, FixedTimespan {  // 2030-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1936234800, FixedTimespan {  // 2031-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1944100800, FixedTimespan {  // 2031-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1967684400, FixedTimespan {  // 2032-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (1976155200, FixedTimespan {  // 2032-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (1999738800, FixedTimespan {  // 2033-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2007604800, FixedTimespan {  // 2033-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2031188400, FixedTimespan {  // 2034-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2039054400, FixedTimespan {  // 2034-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2062638000, FixedTimespan {  // 2035-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2070504000, FixedTimespan {  // 2035-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2094087600, FixedTimespan {  // 2036-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2101953600, FixedTimespan {  // 2036-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2125537200, FixedTimespan {  // 2037-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2133403200, FixedTimespan {  // 2037-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2156986800, FixedTimespan {  // 2038-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2165457600, FixedTimespan {  // 2038-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2189041200, FixedTimespan {  // 2039-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2196907200, FixedTimespan {  // 2039-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2220490800, FixedTimespan {  // 2040-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2228356800, FixedTimespan {  // 2040-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2251940400, FixedTimespan {  // 2041-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2259806400, FixedTimespan {  // 2041-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2283390000, FixedTimespan {  // 2042-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2291256000, FixedTimespan {  // 2042-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2314839600, FixedTimespan {  // 2043-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2322705600, FixedTimespan {  // 2043-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2346894000, FixedTimespan {  // 2044-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2354760000, FixedTimespan {  // 2044-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2378343600, FixedTimespan {  // 2045-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2386209600, FixedTimespan {  // 2045-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2409793200, FixedTimespan {  // 2046-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2417659200, FixedTimespan {  // 2046-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2441242800, FixedTimespan {  // 2047-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2449108800, FixedTimespan {  // 2047-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2472692400, FixedTimespan {  // 2048-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2480558400, FixedTimespan {  // 2048-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2504142000, FixedTimespan {  // 2049-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2512612800, FixedTimespan {  // 2049-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2536196400, FixedTimespan {  // 2050-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2544062400, FixedTimespan {  // 2050-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2567646000, FixedTimespan {  // 2051-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2575512000, FixedTimespan {  // 2051-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2599095600, FixedTimespan {  // 2052-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2606961600, FixedTimespan {  // 2052-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2630545200, FixedTimespan {  // 2053-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2638411200, FixedTimespan {  // 2053-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2661994800, FixedTimespan {  // 2054-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2669860800, FixedTimespan {  // 2054-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2693444400, FixedTimespan {  // 2055-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2701915200, FixedTimespan {  // 2055-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2725498800, FixedTimespan {  // 2056-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2733364800, FixedTimespan {  // 2056-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2756948400, FixedTimespan {  // 2057-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2764814400, FixedTimespan {  // 2057-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2788398000, FixedTimespan {  // 2058-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2796264000, FixedTimespan {  // 2058-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2819847600, FixedTimespan {  // 2059-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2827713600, FixedTimespan {  // 2059-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2851297200, FixedTimespan {  // 2060-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2859768000, FixedTimespan {  // 2060-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2883351600, FixedTimespan {  // 2061-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2891217600, FixedTimespan {  // 2061-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2914801200, FixedTimespan {  // 2062-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2922667200, FixedTimespan {  // 2062-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2946250800, FixedTimespan {  // 2063-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2954116800, FixedTimespan {  // 2063-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (2977700400, FixedTimespan {  // 2064-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (2985566400, FixedTimespan {  // 2064-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3009150000, FixedTimespan {  // 2065-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3017016000, FixedTimespan {  // 2065-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3040599600, FixedTimespan {  // 2066-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3049070400, FixedTimespan {  // 2066-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3072654000, FixedTimespan {  // 2067-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3080520000, FixedTimespan {  // 2067-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3104103600, FixedTimespan {  // 2068-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3111969600, FixedTimespan {  // 2068-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3135553200, FixedTimespan {  // 2069-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3143419200, FixedTimespan {  // 2069-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3167002800, FixedTimespan {  // 2070-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3174868800, FixedTimespan {  // 2070-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3198452400, FixedTimespan {  // 2071-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3206318400, FixedTimespan {  // 2071-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3230506800, FixedTimespan {  // 2072-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3238372800, FixedTimespan {  // 2072-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3261956400, FixedTimespan {  // 2073-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3269822400, FixedTimespan {  // 2073-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3293406000, FixedTimespan {  // 2074-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3301272000, FixedTimespan {  // 2074-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3324855600, FixedTimespan {  // 2075-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3332721600, FixedTimespan {  // 2075-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3356305200, FixedTimespan {  // 2076-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3364171200, FixedTimespan {  // 2076-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3387754800, FixedTimespan {  // 2077-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3396225600, FixedTimespan {  // 2077-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3419809200, FixedTimespan {  // 2078-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3427675200, FixedTimespan {  // 2078-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3451258800, FixedTimespan {  // 2079-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3459124800, FixedTimespan {  // 2079-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3482708400, FixedTimespan {  // 2080-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3490574400, FixedTimespan {  // 2080-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3514158000, FixedTimespan {  // 2081-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3522024000, FixedTimespan {  // 2081-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3545607600, FixedTimespan {  // 2082-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3553473600, FixedTimespan {  // 2082-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3577057200, FixedTimespan {  // 2083-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3585528000, FixedTimespan {  // 2083-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3609111600, FixedTimespan {  // 2084-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3616977600, FixedTimespan {  // 2084-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3640561200, FixedTimespan {  // 2085-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3648427200, FixedTimespan {  // 2085-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3672010800, FixedTimespan {  // 2086-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3679876800, FixedTimespan {  // 2086-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3703460400, FixedTimespan {  // 2087-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3711326400, FixedTimespan {  // 2087-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3734910000, FixedTimespan {  // 2088-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3743380800, FixedTimespan {  // 2088-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3766964400, FixedTimespan {  // 2089-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3774830400, FixedTimespan {  // 2089-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3798414000, FixedTimespan {  // 2090-05-14T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3806280000, FixedTimespan {  // 2090-08-13T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3829863600, FixedTimespan {  // 2091-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3837729600, FixedTimespan {  // 2091-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3861313200, FixedTimespan {  // 2092-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3869179200, FixedTimespan {  // 2092-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3892762800, FixedTimespan {  // 2093-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3900628800, FixedTimespan {  // 2093-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3924212400, FixedTimespan {  // 2094-05-09T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3932683200, FixedTimespan {  // 2094-08-15T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3956266800, FixedTimespan {  // 2095-05-15T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3964132800, FixedTimespan {  // 2095-08-14T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (3987716400, FixedTimespan {  // 2096-05-13T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (3995582400, FixedTimespan {  // 2096-08-12T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (4019166000, FixedTimespan {  // 2097-05-12T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (4027032000, FixedTimespan {  // 2097-08-11T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (4050615600, FixedTimespan {  // 2098-05-11T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (4058481600, FixedTimespan {  // 2098-08-10T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
        (4082065200, FixedTimespan {  // 2099-05-10T03:00:00.000 UTC
            offset: -21600,  // UTC offset -21600, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("EAST"),
        }),
        (4089931200, FixedTimespan {  // 2099-08-09T04:00:00.000 UTC
            offset: -18000,  // UTC offset -21600, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("EASST"),
        }),
    ]},
};


