
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Antarctica/Palmer",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 0,  // UTC offset 0, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("-00"),
        },
        rest: &[
        (-157766400, FixedTimespan {  // 1965-01-01T00:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (-152658000, FixedTimespan {  // 1965-03-01T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (-132955200, FixedTimespan {  // 1965-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (-121122000, FixedTimespan {  // 1966-03-01T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (-101419200, FixedTimespan {  // 1966-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (-86821200, FixedTimespan {  // 1967-04-02T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (-71092800, FixedTimespan {  // 1967-10-01T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (-54766800, FixedTimespan {  // 1968-04-07T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (-39038400, FixedTimespan {  // 1968-10-06T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (-23317200, FixedTimespan {  // 1969-04-06T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (-7588800, FixedTimespan {  // 1969-10-05T04:00:00.000 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (128142000, FixedTimespan {  // 1974-01-23T03:00:00.000 UTC
            offset: -7200,  // UTC offset -10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("ARST"),
        }),
        (136605600, FixedTimespan {  // 1974-05-01T02:00:00.000 UTC
            offset: -10800,  // UTC offset -10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("ART"),
        }),
        (389070000, FixedTimespan {  // 1982-05-01T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (403070400, FixedTimespan {  // 1982-10-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (416372400, FixedTimespan {  // 1983-03-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (434520000, FixedTimespan {  // 1983-10-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (447822000, FixedTimespan {  // 1984-03-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (466574400, FixedTimespan {  // 1984-10-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (479271600, FixedTimespan {  // 1985-03-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (498024000, FixedTimespan {  // 1985-10-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (510721200, FixedTimespan {  // 1986-03-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (529473600, FixedTimespan {  // 1986-10-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (545194800, FixedTimespan {  // 1987-04-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (560923200, FixedTimespan {  // 1987-10-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (574225200, FixedTimespan {  // 1988-03-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (592372800, FixedTimespan {  // 1988-10-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (605674800, FixedTimespan {  // 1989-03-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (624427200, FixedTimespan {  // 1989-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (637124400, FixedTimespan {  // 1990-03-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (653457600, FixedTimespan {  // 1990-09-16T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (668574000, FixedTimespan {  // 1991-03-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (687326400, FixedTimespan {  // 1991-10-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (700628400, FixedTimespan {  // 1992-03-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (718776000, FixedTimespan {  // 1992-10-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (732078000, FixedTimespan {  // 1993-03-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (750225600, FixedTimespan {  // 1993-10-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (763527600, FixedTimespan {  // 1994-03-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (781675200, FixedTimespan {  // 1994-10-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (794977200, FixedTimespan {  // 1995-03-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (813729600, FixedTimespan {  // 1995-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (826426800, FixedTimespan {  // 1996-03-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (845179200, FixedTimespan {  // 1996-10-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (859690800, FixedTimespan {  // 1997-03-30T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (876628800, FixedTimespan {  // 1997-10-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (889930800, FixedTimespan {  // 1998-03-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (906868800, FixedTimespan {  // 1998-09-27T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (923194800, FixedTimespan {  // 1999-04-04T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (939528000, FixedTimespan {  // 1999-10-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (952830000, FixedTimespan {  // 2000-03-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (971582400, FixedTimespan {  // 2000-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (984279600, FixedTimespan {  // 2001-03-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1003032000, FixedTimespan {  // 2001-10-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1015729200, FixedTimespan {  // 2002-03-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1034481600, FixedTimespan {  // 2002-10-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1047178800, FixedTimespan {  // 2003-03-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1065931200, FixedTimespan {  // 2003-10-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1079233200, FixedTimespan {  // 2004-03-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1097380800, FixedTimespan {  // 2004-10-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1110682800, FixedTimespan {  // 2005-03-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1128830400, FixedTimespan {  // 2005-10-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1142132400, FixedTimespan {  // 2006-03-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1160884800, FixedTimespan {  // 2006-10-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1173582000, FixedTimespan {  // 2007-03-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1192334400, FixedTimespan {  // 2007-10-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1206846000, FixedTimespan {  // 2008-03-30T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1223784000, FixedTimespan {  // 2008-10-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1237086000, FixedTimespan {  // 2009-03-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1255233600, FixedTimespan {  // 2009-10-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1270350000, FixedTimespan {  // 2010-04-04T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1286683200, FixedTimespan {  // 2010-10-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1304823600, FixedTimespan {  // 2011-05-08T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1313899200, FixedTimespan {  // 2011-08-21T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1335668400, FixedTimespan {  // 2012-04-29T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1346558400, FixedTimespan {  // 2012-09-02T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1367118000, FixedTimespan {  // 2013-04-28T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1378612800, FixedTimespan {  // 2013-09-08T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1398567600, FixedTimespan {  // 2014-04-27T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1410062400, FixedTimespan {  // 2014-09-07T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1463281200, FixedTimespan {  // 2016-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1471147200, FixedTimespan {  // 2016-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1494730800, FixedTimespan {  // 2017-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1502596800, FixedTimespan {  // 2017-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1526180400, FixedTimespan {  // 2018-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1534046400, FixedTimespan {  // 2018-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1557630000, FixedTimespan {  // 2019-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1565496000, FixedTimespan {  // 2019-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1589079600, FixedTimespan {  // 2020-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1596945600, FixedTimespan {  // 2020-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1620529200, FixedTimespan {  // 2021-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1629000000, FixedTimespan {  // 2021-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1652583600, FixedTimespan {  // 2022-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1660449600, FixedTimespan {  // 2022-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1684033200, FixedTimespan {  // 2023-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1691899200, FixedTimespan {  // 2023-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1715482800, FixedTimespan {  // 2024-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1723348800, FixedTimespan {  // 2024-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1746932400, FixedTimespan {  // 2025-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1754798400, FixedTimespan {  // 2025-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1778382000, FixedTimespan {  // 2026-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1786248000, FixedTimespan {  // 2026-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1809831600, FixedTimespan {  // 2027-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1818302400, FixedTimespan {  // 2027-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1841886000, FixedTimespan {  // 2028-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1849752000, FixedTimespan {  // 2028-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1873335600, FixedTimespan {  // 2029-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1881201600, FixedTimespan {  // 2029-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1904785200, FixedTimespan {  // 2030-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1912651200, FixedTimespan {  // 2030-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1936234800, FixedTimespan {  // 2031-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1944100800, FixedTimespan {  // 2031-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1967684400, FixedTimespan {  // 2032-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (1976155200, FixedTimespan {  // 2032-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (1999738800, FixedTimespan {  // 2033-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2007604800, FixedTimespan {  // 2033-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2031188400, FixedTimespan {  // 2034-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2039054400, FixedTimespan {  // 2034-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2062638000, FixedTimespan {  // 2035-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2070504000, FixedTimespan {  // 2035-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2094087600, FixedTimespan {  // 2036-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2101953600, FixedTimespan {  // 2036-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2125537200, FixedTimespan {  // 2037-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2133403200, FixedTimespan {  // 2037-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2156986800, FixedTimespan {  // 2038-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2165457600, FixedTimespan {  // 2038-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2189041200, FixedTimespan {  // 2039-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2196907200, FixedTimespan {  // 2039-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2220490800, FixedTimespan {  // 2040-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2228356800, FixedTimespan {  // 2040-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2251940400, FixedTimespan {  // 2041-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2259806400, FixedTimespan {  // 2041-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2283390000, FixedTimespan {  // 2042-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2291256000, FixedTimespan {  // 2042-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2314839600, FixedTimespan {  // 2043-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2322705600, FixedTimespan {  // 2043-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2346894000, FixedTimespan {  // 2044-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2354760000, FixedTimespan {  // 2044-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2378343600, FixedTimespan {  // 2045-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2386209600, FixedTimespan {  // 2045-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2409793200, FixedTimespan {  // 2046-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2417659200, FixedTimespan {  // 2046-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2441242800, FixedTimespan {  // 2047-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2449108800, FixedTimespan {  // 2047-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2472692400, FixedTimespan {  // 2048-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2480558400, FixedTimespan {  // 2048-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2504142000, FixedTimespan {  // 2049-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2512612800, FixedTimespan {  // 2049-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2536196400, FixedTimespan {  // 2050-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2544062400, FixedTimespan {  // 2050-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2567646000, FixedTimespan {  // 2051-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2575512000, FixedTimespan {  // 2051-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2599095600, FixedTimespan {  // 2052-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2606961600, FixedTimespan {  // 2052-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2630545200, FixedTimespan {  // 2053-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2638411200, FixedTimespan {  // 2053-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2661994800, FixedTimespan {  // 2054-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2669860800, FixedTimespan {  // 2054-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2693444400, FixedTimespan {  // 2055-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2701915200, FixedTimespan {  // 2055-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2725498800, FixedTimespan {  // 2056-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2733364800, FixedTimespan {  // 2056-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2756948400, FixedTimespan {  // 2057-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2764814400, FixedTimespan {  // 2057-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2788398000, FixedTimespan {  // 2058-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2796264000, FixedTimespan {  // 2058-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2819847600, FixedTimespan {  // 2059-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2827713600, FixedTimespan {  // 2059-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2851297200, FixedTimespan {  // 2060-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2859768000, FixedTimespan {  // 2060-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2883351600, FixedTimespan {  // 2061-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2891217600, FixedTimespan {  // 2061-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2914801200, FixedTimespan {  // 2062-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2922667200, FixedTimespan {  // 2062-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2946250800, FixedTimespan {  // 2063-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2954116800, FixedTimespan {  // 2063-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (2977700400, FixedTimespan {  // 2064-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (2985566400, FixedTimespan {  // 2064-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3009150000, FixedTimespan {  // 2065-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3017016000, FixedTimespan {  // 2065-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3040599600, FixedTimespan {  // 2066-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3049070400, FixedTimespan {  // 2066-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3072654000, FixedTimespan {  // 2067-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3080520000, FixedTimespan {  // 2067-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3104103600, FixedTimespan {  // 2068-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3111969600, FixedTimespan {  // 2068-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3135553200, FixedTimespan {  // 2069-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3143419200, FixedTimespan {  // 2069-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3167002800, FixedTimespan {  // 2070-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3174868800, FixedTimespan {  // 2070-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3198452400, FixedTimespan {  // 2071-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3206318400, FixedTimespan {  // 2071-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3230506800, FixedTimespan {  // 2072-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3238372800, FixedTimespan {  // 2072-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3261956400, FixedTimespan {  // 2073-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3269822400, FixedTimespan {  // 2073-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3293406000, FixedTimespan {  // 2074-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3301272000, FixedTimespan {  // 2074-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3324855600, FixedTimespan {  // 2075-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3332721600, FixedTimespan {  // 2075-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3356305200, FixedTimespan {  // 2076-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3364171200, FixedTimespan {  // 2076-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3387754800, FixedTimespan {  // 2077-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3396225600, FixedTimespan {  // 2077-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3419809200, FixedTimespan {  // 2078-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3427675200, FixedTimespan {  // 2078-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3451258800, FixedTimespan {  // 2079-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3459124800, FixedTimespan {  // 2079-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3482708400, FixedTimespan {  // 2080-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3490574400, FixedTimespan {  // 2080-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3514158000, FixedTimespan {  // 2081-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3522024000, FixedTimespan {  // 2081-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3545607600, FixedTimespan {  // 2082-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3553473600, FixedTimespan {  // 2082-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3577057200, FixedTimespan {  // 2083-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3585528000, FixedTimespan {  // 2083-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3609111600, FixedTimespan {  // 2084-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3616977600, FixedTimespan {  // 2084-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3640561200, FixedTimespan {  // 2085-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3648427200, FixedTimespan {  // 2085-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3672010800, FixedTimespan {  // 2086-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3679876800, FixedTimespan {  // 2086-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3703460400, FixedTimespan {  // 2087-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3711326400, FixedTimespan {  // 2087-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3734910000, FixedTimespan {  // 2088-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3743380800, FixedTimespan {  // 2088-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3766964400, FixedTimespan {  // 2089-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3774830400, FixedTimespan {  // 2089-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3798414000, FixedTimespan {  // 2090-05-14T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3806280000, FixedTimespan {  // 2090-08-13T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3829863600, FixedTimespan {  // 2091-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3837729600, FixedTimespan {  // 2091-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3861313200, FixedTimespan {  // 2092-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3869179200, FixedTimespan {  // 2092-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3892762800, FixedTimespan {  // 2093-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3900628800, FixedTimespan {  // 2093-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3924212400, FixedTimespan {  // 2094-05-09T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3932683200, FixedTimespan {  // 2094-08-15T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3956266800, FixedTimespan {  // 2095-05-15T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3964132800, FixedTimespan {  // 2095-08-14T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (3987716400, FixedTimespan {  // 2096-05-13T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (3995582400, FixedTimespan {  // 2096-08-12T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (4019166000, FixedTimespan {  // 2097-05-12T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (4027032000, FixedTimespan {  // 2097-08-11T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (4050615600, FixedTimespan {  // 2098-05-11T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (4058481600, FixedTimespan {  // 2098-08-10T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
        (4082065200, FixedTimespan {  // 2099-05-10T03:00:00.000 UTC
            offset: -14400,  // UTC offset -14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("CLT"),
        }),
        (4089931200, FixedTimespan {  // 2099-08-09T04:00:00.000 UTC
            offset: -10800,  // UTC offset -14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("CLST"),
        }),
    ]},
};


