
// ------
// This file is autogenerated!
// Any changes you make may be overwritten.
// ------


use std::borrow::Cow;
use datetime::zone::{StaticTimeZone, FixedTimespanSet, FixedTimespan};

pub static ZONE: StaticTimeZone<'static> = StaticTimeZone {
    name: "Europe/Kirov",
    fixed_timespans: FixedTimespanSet {
        first: FixedTimespan {
            offset: 11928,  // UTC offset 11928, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("LMT"),
        },
        rest: &[
        (-1593825528, FixedTimespan {  // 1919-06-30T22:41:12.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (-1247540400, FixedTimespan {  // 1930-06-20T21:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (354916800, FixedTimespan {  // 1981-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (370724400, FixedTimespan {  // 1981-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (386452800, FixedTimespan {  // 1982-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (402260400, FixedTimespan {  // 1982-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (417988800, FixedTimespan {  // 1983-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (433796400, FixedTimespan {  // 1983-09-30T19:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (449611200, FixedTimespan {  // 1984-03-31T20:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (465343200, FixedTimespan {  // 1984-09-29T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (481068000, FixedTimespan {  // 1985-03-30T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (496792800, FixedTimespan {  // 1985-09-28T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (512517600, FixedTimespan {  // 1986-03-29T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (528242400, FixedTimespan {  // 1986-09-27T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (543967200, FixedTimespan {  // 1987-03-28T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (559692000, FixedTimespan {  // 1987-09-26T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (575416800, FixedTimespan {  // 1988-03-26T22:00:00.000 UTC
            offset: 18000,  // UTC offset 14400, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+05"),
        }),
        (591141600, FixedTimespan {  // 1988-09-24T22:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (606866400, FixedTimespan {  // 1989-03-25T22:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (622594800, FixedTimespan {  // 1989-09-23T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (638319600, FixedTimespan {  // 1990-03-24T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (654649200, FixedTimespan {  // 1990-09-29T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (670374000, FixedTimespan {  // 1991-03-30T23:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (701820000, FixedTimespan {  // 1992-03-28T22:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (717548400, FixedTimespan {  // 1992-09-26T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (733273200, FixedTimespan {  // 1993-03-27T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (748998000, FixedTimespan {  // 1993-09-25T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (764722800, FixedTimespan {  // 1994-03-26T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (780447600, FixedTimespan {  // 1994-09-24T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (796172400, FixedTimespan {  // 1995-03-25T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (811897200, FixedTimespan {  // 1995-09-23T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (828226800, FixedTimespan {  // 1996-03-30T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (846370800, FixedTimespan {  // 1996-10-26T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (859676400, FixedTimespan {  // 1997-03-29T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (877820400, FixedTimespan {  // 1997-10-25T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (891126000, FixedTimespan {  // 1998-03-28T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (909270000, FixedTimespan {  // 1998-10-24T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (922575600, FixedTimespan {  // 1999-03-27T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (941324400, FixedTimespan {  // 1999-10-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (954025200, FixedTimespan {  // 2000-03-25T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (972774000, FixedTimespan {  // 2000-10-28T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (985474800, FixedTimespan {  // 2001-03-24T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1004223600, FixedTimespan {  // 2001-10-27T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1017529200, FixedTimespan {  // 2002-03-30T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1035673200, FixedTimespan {  // 2002-10-26T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1048978800, FixedTimespan {  // 2003-03-29T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1067122800, FixedTimespan {  // 2003-10-25T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1080428400, FixedTimespan {  // 2004-03-27T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1099177200, FixedTimespan {  // 2004-10-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1111878000, FixedTimespan {  // 2005-03-26T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1130626800, FixedTimespan {  // 2005-10-29T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1143327600, FixedTimespan {  // 2006-03-25T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1162076400, FixedTimespan {  // 2006-10-28T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1174777200, FixedTimespan {  // 2007-03-24T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1193526000, FixedTimespan {  // 2007-10-27T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1206831600, FixedTimespan {  // 2008-03-29T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1224975600, FixedTimespan {  // 2008-10-25T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1238281200, FixedTimespan {  // 2009-03-28T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1256425200, FixedTimespan {  // 2009-10-24T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1269730800, FixedTimespan {  // 2010-03-27T23:00:00.000 UTC
            offset: 14400,  // UTC offset 10800, DST offset 3600
            is_dst: true,
            name:   Cow::Borrowed("+04"),
        }),
        (1288479600, FixedTimespan {  // 2010-10-30T23:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
        (1301180400, FixedTimespan {  // 2011-03-26T23:00:00.000 UTC
            offset: 14400,  // UTC offset 14400, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+04"),
        }),
        (1414274400, FixedTimespan {  // 2014-10-25T22:00:00.000 UTC
            offset: 10800,  // UTC offset 10800, DST offset 0
            is_dst: false,
            name:   Cow::Borrowed("+03"),
        }),
    ]},
};


